# Generated by Django 5.1.2 on 2024-11-10 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Childname', models.CharField(max_length=200)),
                ('ChildId', models.IntegerField(blank=True, null=True)),
                ('ChildCertificate', models.CharField(max_length=200)),
                ('BrithDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DoctorId', models.IntegerField(blank=True, null=True)),
                ('Name', models.CharField(max_length=200)),
                ('Specification', models.CharField(max_length=100)),
                ('AvailableHours', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParentsId', models.IntegerField(blank=True, null=True)),
                ('ParentsNID', models.IntegerField(blank=True, null=True)),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Phone', models.IntegerField(max_length=20)),
                ('Address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ConsultationId', models.IntegerField(max_length=50)),
                ('ConsultationDate', models.IntegerField(blank=True, null=True)),
                ('ConsultationTime', models.TimeField(blank=True, null=True)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('ChildId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChildCare.child')),
            ],
        ),
        migrations.CreateModel(
            name='HealthInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HealthInfoId', models.IntegerField(max_length=100)),
                ('Vaccination', models.CharField(max_length=200)),
                ('Allergies', models.CharField(max_length=200)),
                ('MedicalCondition', models.CharField(max_length=200)),
                ('CheckupDate', models.DateTimeField(blank=True, null=True)),
                ('ChildId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChildCare.child')),
            ],
        ),
        migrations.CreateModel(
            name='LearningPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlanId', models.IntegerField(max_length=50)),
                ('PlanName', models.CharField(max_length=200)),
                ('Descrption', models.TextField(blank=True, null=True)),
                ('AgeGroup', models.IntegerField(blank=True, null=True)),
                ('ChildId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChildCare.child')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='ParentsId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ChildCare.parents'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ScheduleId', models.IntegerField(max_length=50)),
                ('SchoolType', models.IntegerField(max_length=100)),
                ('ChildId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChildCare.child')),
            ],
        ),
    ]
