# Generated by Django 5.1.2 on 2024-11-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChildCare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='ChildCertificate',
            field=models.ImageField(upload_to='certificate/'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='ConsultationDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='ConsultationId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthinfo',
            name='Allergies',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='healthinfo',
            name='HealthInfoId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthinfo',
            name='Vaccination',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='learningplan',
            name='PlanId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parents',
            name='Phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='ScheduleId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='SchoolType',
            field=models.CharField(max_length=200),
        ),
    ]
