# Generated by Django 5.1.2 on 2024-12-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChildCare', '0002_alter_child_childcertificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='BrithDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
